### ISSUE TITLE
Incompatibility with ChestSort

### ISSUE THREAD

**Issue by Name-Searcher** [percyqaz/Shulkerbox#7] opened 2023-09-04 07:17 UTC
sometimes when i quickly open a shulker and shift click stuff into it the items aren't saved after closing the inventory 

at first i wasn't certain this was happening but i just had my pickaxe disappear so now I'm sure that is the issue

**Comment by Name-Searcher** [comment] 2023-09-04 07:29
I was using the version from spigotmc.org which hasn't been updated

Just updated it to the github version not sure if that would change anything

**Comment by percyqaz** [comment] 2023-09-04 07:43
Hi, thanks for reporting this

Can you try and capture this on video/as a gif so I can see what this looks like ingame?
Is there a particular method or script you use to do this so quickly?

**Comment by Name-Searcher** [comment] 2023-09-04 09:19
I have a couple other plugins but none that could interfere except one for sorting (chestsort) but it doesn't seem to function with shulkers/enderchest opened from inventory.

I can't really replicate the bug so I have no clue how to capture it but it has happened twice in about 2 weeks
Once from right clicking a shulker in inventory and shift clicking my tools into it and the other time before that from moving blocks into a shulker that was in my enderchest (both done with normal shift click in quick succession).

Current plugin list: BBOutlineReloaded, BedrockPlayerManager, ChatFilter, ChestSort, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, floodgate, GeyserSkinManager, InteractiveChat, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, PlaceholderAPI, ProtocolLib, SilkSpawners, SmileyPlayerTrader, TAB, UltimateInventory, Vault, VillagerSaver, WorldEdit, WorldGuard.

**Comment by Name-Searcher** [comment] 2023-09-04 10:04
yeah that is the one i will remove it see if that fixes it

**Comment by percyqaz** [comment] 2023-09-04 12:45
I've done some testing myself and I do think ChestSort is the culprit

Here's what I think happened:
1. You open a shulkerbox from your inventory
![image](https://github.com/percyqaz/Shulkerbox/assets/21290233/d9254de7-ce2f-4c8c-8b03-d226fc82de13)

2. You take items out/put items in
![image](https://github.com/percyqaz/Shulkerbox/assets/21290233/a38775a2-87f5-4135-ae85-a909075f5dfe)

3. You sort your inventory (for example by enabling the double-click to sort setting)
![image](https://github.com/percyqaz/Shulkerbox/assets/21290233/b2c776f3-4083-4345-b361-7793f988dd5d)

4. You close the shulker box - At the moment you close the shulker box it will try to save the data to this slot, but the shulker box has moved
![image](https://github.com/percyqaz/Shulkerbox/assets/21290233/1648ae6b-b30d-473b-bfc7-c019ddd751fa)

5. Result: After closing the shulker box the change is not saved, so there is a duplicate stack of ancient debris inside it

If that sounds like what you did, that will be the cause of the items vanishing, if not it could still be something else that needs looking into

There are similar dupes you can do if you have automatic ender chest sorting turned on

Sorry about your pickaxe and other items :( Because this can happen when a plugin can move items around, I make it prominent in the description of the plugin that this can cause duplication and that server owners should be careful of this when installing

For now you should not use both plugins at the same time

I will go and think about how this could be fixed, I notice that ChestSort has an API so I might be able to disable inventory sorting while a shulker box is open

**Comment by Name-Searcher** [comment] 2023-09-04 14:21
i never sort my inventory while having shulkers open and i especially never sort my enderchest since it would mess up my manual sorting i mostly used it for auto filling chests (which is automatically disabled on shulkers opened this way) so i think it was some other bug that happened with chestsort

**Comment by KyrVorga** [comment] 2023-09-04 21:42
I also had many compatibility conflicts with Chestsort when I installed this plugin. Removing Chestsort is a small price, especially when players can use client-side sorters.

**Comment by percyqaz** [comment] 2023-09-05 20:25
> i never sort my inventory while having shulkers open and i especially never sort my enderchest since it would mess up my manual sorting i mostly used it for auto filling chests (which is automatically disabled on shulkers opened this way) so i think it was some other bug that happened with chestsort

If this is true then I'm pretty stumped on the cause of the bug
Do you have the setting on where shift-clicking an empty slot sorts your inventory? If so it's possible that while shift-clicking an item you accidentally clicked a second time on the now-empty slot and sorted your inventory
For some reason changes aren't saved to the shulkerbox even if it didn't move so as long as no items moved in your inventory you might not realise you did this
That's the only explanation I can think of so let me know if you do indeed have that setting on

I'll have a crack at adding compatibility for ChestSort later this week since it's a pretty awesome plugin and it would be nice if they worked together - It should be easy using their API

**Comment by percyqaz** [comment] 2023-09-06 21:44
Good news, adding compatibility for ChestSort was exactly as easy as expected - I'll do a bit more testing tomorrow and then release an update

At the very least after installing the new version, ChestSort should no longer be the problem, so if you still experience an issue I'll investigate the rest of your plugins list

Thanks again for reporting this bug, the plugin will be improved as a result :)

**Closed** 2023-09-16 07:12 UTC
Labels: bug: compatibility
