### ISSUE TITLE
Duplication with Crazy Crates and potentially other plugins

### ISSUE THREAD

**Issue by Silvereddark** [percyqaz/Shulkerbox#8] opened 2023-09-15 17:57 UTC
When in any inventory locked menu such as opening a crate,

A player can open their shulker inventory and move things out of it. The inventory does not save the moved items and reverts to its previous mode. Duplicating items.

Example Process that caused it.
1.) Insert item into shulker
2.)Preview Crate contents
3.) Open Shulker using right click
4.) Remove item from shuker (In this case a diamond)
5.) Reopen shulker 
6.) Take item out again.

2x diamonds now. 

May be an issue in inventory saving. Unsure.

**Comment by percyqaz** [comment] 2023-09-16 07:11
Thanks for reporting this, I'll take a look at what the issue is
Is this the right plugin? https://www.spigotmc.org/resources/crazy-crates.17599/

For now you should not use both on the same server

**Comment by Silvereddark** [comment] 2023-09-16 13:48
Yup that's the one!! If you need any info lemme know

**Comment by percyqaz** [comment] 2023-09-16 23:29
Hi, I'm struggling to find the problem you're describing, can you provide some screenshots of the process, and possibly also relevant crate config if you don't mind sharing?

**Comment by percyqaz** [comment] 2023-12-08 01:15
Closing this as I was unable to replicate it without further details
If anyone still needs this investigated, feel free to comment on this thread or open another issue

**Closed by percyqaz** 2023-12-08 01:15 UTC
Labels: bug: compatibility
